#!/bin/sh

# Copyright (C) 2026 vad-b
# SPDX-License-Identifier: GPL-3.0-only

[ "$ACTION" = ifup -o "$ACTION" = ifupdate ] || exit 0
[ "$ACTION" = ifupdate -a -z "$IFUPDATE_ADDRESSES" -a -z "$IFUPDATE_DATA" ] && exit 0

tailscale_enable="$(uci -q get luci-app-tailscale-ng.settings.enabled)"
[ "$tailscale_enable" = "1" ] || exit 0

sleep 10

/etc/init.d/luci-app-tailscale-ng start >/dev/null 2>&1 &
